version: '3.7'
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:9000
    volumes:
      - ./web:/code
    ports:
      - "9000:9000"
    depends_on:
      - db
    networks:
      psycho-net:


  db:
    container_name: mysql
    restart: always
    image: mysql:5.7

    environment:
      MYSQL_ROOT_PASSWORD: 'psycho'
      MYSQL_DATABASE: 'psycho'
      MYSQL_USER: 'psycho'
      MYSQL_PASSWORD: 'Celeron!1'
      MYSQL_ROOT_HOST: %

    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      psycho-net:
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci --skip-character-set-client-handshake


networks:
  psycho-net:
    driver: bridge
    name: psycho-net
