version: '3.7'
services:
  django:
    container_name: ${WEB_NAME}
    hostname: ${WEB_NAME}
    restart: always
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:${DJANGO_PORT}
    volumes:
      - ./web:/code
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"
    depends_on:
      - db
    networks:
      psycho-net:
        aliases:
          - ${WEB_NAME}


  db:
    restart: always
    image: mysql:5.7

    env_file:
      - .env

    environment:
      MYSQL_ROOT_PASSWORD: 'psycho'
      MYSQL_DATABASE: 'psycho'
      MYSQL_USER: 'psycho'
      MYSQL_PASSWORD: 'Celeron!1'

    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      psycho-net:
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci --skip-character-set-client-handshake


networks:
  psycho-net:
    driver: bridge
    name: psycho-net
