# Generated by Django 2.1.5 on 2019-02-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consult', '0002_auto_20190208_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='quote',
            field=models.TextField(blank=True),
        ),
    ]
