# Generated by Django 2.1.5 on 2019-02-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consult', '0003_auto_20190208_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='themes',
            field=models.ManyToManyField(to='consult.Theme'),
        ),
    ]
