# Generated by Django 2.2b1 on 2019-02-17 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consult', '0004_specialist_themes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='themes',
            field=models.ManyToManyField(blank=True, to='consult.Theme'),
        ),
    ]
