# Generated by Django 2.2b1 on 2019-02-17 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consult', '0005_auto_20190217_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
