# Generated by Django 2.2b1 on 2019-02-17 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consult', '0006_auto_20190217_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='degree',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='experience',
            field=models.IntegerField(blank=True),
        ),
    ]
