# Generated by Django 2.1.5 on 2019-02-18 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consult', '0008_auto_20190218_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'open'), ('CANCELED', 'canceled'), ('PENDING', 'pending'), ('EXPIRED', 'expired'), ('FAILED', 'failed'), ('PAID', 'paid')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consult.Enroll')),
            ],
        ),
    ]
