# Generated by Django 2.1.3 on 2019-03-22 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consult', '0009_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='timeslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enroll', to='consult.TimeSlot'),
        ),
    ]
