# Generated by Django 2.1.7 on 2019-04-05 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consult', '0010_auto_20190322_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('sequence', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='enroll',
            name='timeslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolls', to='consult.TimeSlot'),
        ),
    ]
