# Generated by Django 2.1.7 on 2019-04-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consult', '0011_auto_20190405_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='methods',
            field=models.ManyToManyField(blank=True, to='consult.Method'),
        ),
    ]
