# Generated by Django 2.1.7 on 2019-04-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consult', '0013_auto_20190409_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='specialist',
            name='education_add',
            field=models.TextField(blank=True),
        ),
    ]
