# Generated by Django 2.2.1 on 2019-05-13 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consult', '0015_auto_20190502_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='promo',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='consult.Specialist'),
        ),
    ]
