# Generated by Django 2.2.1 on 2019-05-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consult', '0018_auto_20190517_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
