# Generated by Django 2.2.1 on 2019-05-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consult', '0019_specialist_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='notify',
            field=models.BooleanField(default=False),
        ),
    ]
