# Generated by Django 2.2.1 on 2019-05-22 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consult', '0020_payment_notify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='timeslot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enroll', to='consult.TimeSlot'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='enroll',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='consult.Enroll'),
        ),
    ]
