# Generated by Django 2.2.1 on 2019-05-28 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consult', '0021_auto_20190522_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ('start_time',)},
        ),
    ]
