# Generated by Django 2.2.1 on 2019-06-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consult', '0025_auto_20190610_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='authors',
            field=models.ManyToManyField(blank=True, null=True, to='consult.Specialist'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webinar',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='webinar',
            name='status',
            field=models.CharField(choices=[('hidden', 'Скрыт'), ('enroll_open', 'Запись открыта'), ('enroll_closed', 'Запись закрыта'), ('ended', 'Завершен')], default='hidden', max_length=10),
        ),
        migrations.AddField(
            model_name='webinar',
            name='themes',
            field=models.ManyToManyField(blank=True, null=True, to='consult.Theme'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
