# Generated by Django 2.2.1 on 2019-06-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consult', '0026_auto_20190610_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='authors',
            field=models.ManyToManyField(blank=True, to='consult.Specialist'),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='themes',
            field=models.ManyToManyField(blank=True, to='consult.Theme'),
        ),
    ]
