# Generated by Django 2.2.1 on 2019-06-13 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consult', '0027_auto_20190610_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webinarenroll',
            name='Webinar',
        ),
        migrations.AddField(
            model_name='webinarenroll',
            name='webinar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrolls', to='consult.Webinar'),
        ),
    ]
