# Generated by Django 2.2.1 on 2019-06-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consult', '0030_auto_20190613_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='authors',
            field=models.ManyToManyField(blank=True, to='consult.WebinarAuthor'),
        ),
    ]
